# Generated by Django 5.1 on 2024-08-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='visiblity',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('members_only', 'Members Only'), ('unlisted', 'Unlisted')], default='public', max_length=100),
        ),
    ]
